version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app  # Change this path as per your setup
permissions:
  - object: /home/ec2-user/app
    owner: ec2-user
    group: ec2-user
hooks:
  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 30
      runas: ec2-user
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 30
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 30
      runas: ec2-user
