name: Deploy to AWS CodePipeline

on:
  push:
    branches:
      - main  # Change this if your deployment branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change this to your AWS region

      - name: Check if AWS CodePipeline Exists
        id: check_pipeline
        run: |
          PIPELINE_NAME="my-nodejs-pipeline"  # Change this to your actual pipeline name
          PIPELINE_STATUS=$(aws codepipeline get-pipeline-state --name "$PIPELINE_NAME" --query "stageStates[0].actionStates[0].latestExecution.status" --output text 2>/dev/null || echo "NOT_FOUND")

          if [[ "$PIPELINE_STATUS" == "NOT_FOUND" ]]; then
            echo "Pipeline does not exist. Please create it in AWS CodePipeline first."
            exit 1
          else
            echo "Pipeline exists. Triggering execution..."
          fi

      - name: Start AWS CodePipeline Execution
        run: |
          aws codepipeline start-pipeline-execution --name my-nodejs-pipeline  # Change this to your pipeline name
